# Generated by Django 3.1.3 on 2020-11-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, upload_to='collections'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
